#!/usr/bin/env python3
"""تولید embedded.c شامل فایل‌های بازی برای جاسازی در فایل exe"""
import os
import sys

GAME_DIR = os.path.join(os.path.dirname(__file__), '..', 'game')
OUT = os.path.join(os.path.dirname(__file__), 'embedded.c')

def collect(root):
    items = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fn in sorted(filenames):
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace('\\', '/')
            items.append((rel, full))
    return items

def main():
    items = collect(GAME_DIR)
    parts = []
    parts.append('/* auto-generated by gen_embed.py */')
    parts.append('#include <stddef.h>')
    for i, (rel, full) in enumerate(items):
        with open(full, 'rb') as f:
            data = f.read()
        name = f'_f{i}'
        parts.append(f'static const unsigned char {name}[{len(data)}] = {{')
        line = []
        for b in data:
            line.append(str(b))
            if len(line) >= 24:
                parts.append(','.join(line) + ',')
                line = []
        if line:
            parts.append(','.join(line) + ',')
        parts.append('};')
    parts.append('static const EmbFile EMBEDDED[] = {')
    for i, (rel, full) in enumerate(items):
        parts.append(f'  {{"{rel}", _f{i}, sizeof(_f{i})}},')
    parts.append('};')
    parts.append('static const unsigned int EMBEDDED_COUNT = sizeof(EMBEDDED)/sizeof(EMBEDDED[0]);')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(parts) + '\n')
    total = sum(os.path.getsize(full) for _, full in items)
    print(f'embedded.c generated: {len(items)} files, {total} bytes -> {OUT}')

if __name__ == '__main__':
    main()
